### ISSUE TITLE
Optimizer and dashboard uses different units for workload

### ISSUE THREAD

**Issue by rosogon** [SeaCloudsEU/SeaCloudsPlatform#182]
Optimizer: requests/minute
Dashboard: requests/second

The dashboard should change the property in the json before sending to the aam writer.

**Comment by perezp** [comment]
Thanks for raising the issue. Currently I have both methods implemented because we have already changed among these options along the project. 
So, I can deal with this issue easily. 
Let me know which one the dashboard is collecting and I will use the correct method for this case.

**Comment by rosogon** [comment]
For me, it is a presentation issue. Let @adriannieto answer the current unit.

**Comment by perezp** [comment]
OK

**Comment by adriannieto** [comment]
I will change the text to have an unified unit spec across aamwriter/optimizer

**Comment by rosogon** [comment]
@adriannieto : aamwriter uses req_per_min for workload. Could you translate the value to req/min? Thanks

**Comment by adriannieto** [comment]
This should be closed, but I can't do it.
