### ISSUE TITLE
Migrate Dashboard Module to template based JS framework

### ISSUE THREAD

**Issue by adriannieto** [SeaCloudsEU/SeaCloudsPlatform#9]
The Dashboard must be developed using client side template based websites. NodeJS and Handlebars could be a nice option.

**Comment by andreaturli** [comment]
What's the status of this issue? Is it still valid after 5 months?

**Comment by adriannieto** [comment]
This is currently WIP in https://github.com/adriannieto/SeaCloudsPlatform/tree/feature/dashboard-v2

**Comment by adriannieto** [comment]
Closed by #70
