### ISSUE TITLE
Seaclouds creation of files and folders around the system.

### ISSUE THREAD

**Issue by perezp** [SeaCloudsEU/SeaCloudsPlatform#95]
https://github.com/SeaCloudsEU/SeaCloudsPlatform/blob/master/discoverer/src/main/java/eu/seaclouds/platform/discoverer/core/Discoverer.java#L48 

sets up the address to create a folder in the user HOME. 
Use "target" folder whenever possible.

**Comment by PaoloCifariello** [comment]
@perezp since now we use a database service I think that this can be close.

**Comment by perezp** [comment]
@PaoloCifariello Right
